version: "3"

services:
    db:
      build:
        context: .
        dockerfile: ./docker/db/Dockerfile
      image: db
      command: mysqld --character-set-server=utf8mb4 --character-set-filesystem=utf8mb4
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql
      environment:
        MYSQL_DATABASE: sample 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: sample
        MYSQL_PASSWORD: sample 
      networks:
        - sample 
volumes:
  db:
networks:
  sample:
